language: cpp

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "EcAS79Tp12IZnW1ddUTE2MJMhHl73SRAaXpAZYS70SdkDhq8YsMoDsQTRTqzE1Ev63OW1mgl3kcUp5pr24jiNrIMDVNKWtyn1rk9dTCs8fHOEUXNszNsu5qKWUiqSnrU5OYI4F4TJVpJIjyhQ9l/2fio43MiJWoJ2dV1knThrIql1tRRWgFcUFWmbI9eC9bjwP43KuPOb+uMtFbGEj9lH7XOgJ0CwaPhkZgfWaQ/7szItCOorAXVZ8IyDt9cLmjctGVlhzgGgfJBk0/RhkrQsz1ODvCSxcAWyznIHCgAJzsMnVtNkBU77AtiF/ycikw6R3iEkFN6wFwnx8j4+ZBkonzB0wMV8s799EPaocsvN6AfV7aDTLfIOBlqlSdQW6Gzbr7UPvbMgSb/ne1UeXL9fnjy5jgEPGuDTE6/KsPI1SRbcI3GZfWau0yAauqB/AQcY57InhXHvznIH3yfAnrW2u+Btr9UUPy6QQHLeenKpP4d9fBPSz6Fs+G1f2m9OkjZI9EpoYQDdHavkYqDxeYbn1NFoe52VfUyl9xG04e9Xo2AzKCYm1mLysj3LABOE7JTuRYXTh6/UjQWQqHvx+nEWHutJN93wG+oGDFzqjQ8k+4NVVXm2hilZM3P79UJZwrzfH0AS9NKZAyhA9NbpuPAU3A6ncaKXjPyR3R3xHvCryw="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
