language: cpp

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "OpMEjqqPAYKSlu58VvqD3ljfUZuFnzLxYrYGS2hjZR2nLYnUoSeG7L0eZHwk2JCVfYdkM4r8we3t0czDsFZlohPRRrLAXYSp6xGeTAUcJUCAmsAStKGSuW8Fpq8USFcKBGywx1Kk9VxKuwK7V5ZUSFOTzi8X+Yqe7yU1waKhPB45GVWRW2Nr4amQOlR7piUj6jKnyJrOmb/oAJ0Ufkl6EAHZ1Ca0mcMeu36WKX2DY42L2c947fA0vsmkX/3rCbStNutqXbFdMRqH/6+ozrCS3Pi2ukIilJisx7metxDL4b1b3k6XFzRP43L0O3He9jIyY4zVqZT4fNCZ2wpiPRbWc5U6J+ehB/1414LcbxrQPsbUJchDh/Mn441L2BkLz++f+3SGEX+eSedBnL4DgYBkYTiwcEC1/yfj1dfQdpck/Ox64qI5JJOxXozNskXqXtnJVy+i84guxa/zYkzxWy1G5PpwV5HHL9su1yMnQaC5kL7HxStjvRxmMgUcAsEkHT9F5nhbty6NSjRx4bopNXgLKtwCWzoyNPjOHbWYkhvV/FDwaEsI+ARvCStdWldl+CvFN1yAT0Q44Mo0rkas3GemgTM7kZx/gugJJ7nY51cJI33Fab6WBHN997buN//C/AE8SFp8iJ4ftibHED5s5pz3xhPDBXv8+ebcT6dPv3y5z8c="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
