sudo: required

arch:
  packages:
    - cmake
    - git
  script:
    - cmake . -DCMAKE_INSTALL_PREFIX=/usr
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
